
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    const androidLarge2 = AndroidLarge2();
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(
          children: const [
            AndroidLarge2(),
          ],
        ),
      ),
    );
  }
}

class AndroidLarge2 extends StatelessWidget {
  const AndroidLarge2({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 800,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 50,
                  padding: const EdgeInsets.symmetric(vertical: 12),
                  decoration: ShapeDecoration(
                    color: const Color(0xFFA2F9FF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(10),
                        bottomRight: Radius.circular(10),
                      ),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 32,
                        height: 32,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(
                          shape: BoxShape.circle,
                        ),
                        child: Stack(
                          children: [
                            // Add child widgets for this Stack
                          ],
                        ),
                      ),
                      const SizedBox(width: 47),
                      SizedBox(
                        width: 141,
                        child: Text(
                          'Hi, Abhiram 👋',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF2D3B70),
                            fontSize: 20,
                            fontFamily: 'Nunito',
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ),
                      const SizedBox(width: 47),
                      Container(padding: const EdgeInsets.all(4)),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 296,
                top: 5,
                child: Container(
                  width: 38,
                  height: 38,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: const NetworkImage(
                          "https://via.placeholder.com/38x38"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(13),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 90,
                child: Container(
                  width: 151,
                  height: 207,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4F3FAB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(19),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 196,
                top: 90,
                child: Container(
                  width: 151,
                  height: 207,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF4F3FAB),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(19),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 186,
                top: 337,
                child: Container(
                  width: 152,
                  height: 264,
                  decoration: ShapeDecoration(
                    color: const Color(0x5BF1EDED),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 337,
                child: Container(
                  width: 150,
                  height: 146,
                  decoration: ShapeDecoration(
                    color: const Color(0x8ED9D9D9),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(17),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 120,
                top: 100,
                child: Container(
                  width: 32.36,
                  height: 32.36,
                  child: Stack(
                    children: [
                      // Add child widgets for this Stack
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 304,
                top: 100,
                child: Container(
                  width: 32.36,
                  height: 32.36,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      // Add child widgets for this Stack
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 732,
                child: Container(
                  width: 360,
                  height: 68,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(20),
                        topRight: Radius.circular(20),
                      ),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 360,
                          height: 68,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 207,
                        top: 15,
                        child: Container(
                          width: 38,
                          height: 38,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              // Add child widgets for this Stack
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 112,
                        top: 15,
                        child: Container(
                          width: 38,
                          height: 38,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              // Add child widgets for this Stack
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 302,
                        top: 15,
                        child: Container(
                          width: 38,
                          height: 38,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(
                            children: [
                              // Add child widgets for this Stack
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 15,
                        child: Container(
                          width: 38,
                          height: 38,
                          clipBehavior: Clip.antiAlias,
                          decoration:
                              BoxDecoration(color: Colors.white.withOpacity(0)),
                          child: Stack(
                            children: [
                              // Add child widgets for this Stack
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
